version: '3'
services:
  cloudreve:
    image: xiami110/cloudreve
    container_name: cloudreve
    restart: always
    ports:
      - "5212:5212"
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: 1m
    volumes:
      - $PWD/avatar:/cloudreve/avatar
      - $PWD/config:/cloudreve/config
      - $PWD/db:/cloudreve/db
      - $PWD/uploads:/cloudreve/uploads
