version: '3'
services:
  frps:
    image: xiami110/frps
    container_name: frps
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
    network_mode: bridge
    volumes:
      - /etc/locltime:/etc/localtime:ro
      - $PWD/frps/frps.ini:/etc/frp/frps.ini
