version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-actions-dependencies:
        update-types: [minor, patch]

  - package-ecosystem: "docker"
    directories:
      - "/*"
    schedule:
      interval: "weekly"
    groups:
      minor-docker-dependencies:
        update-types: [minor, patch]
