version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "aria2"
      - "mindustry"
      - "ntpd-rs"
      - "openlist"
      - "qbittorrentee"
      - "samba"
    schedule:
      interval: "weekly"
