name: LibreTranslate
run-name: "Docker Build: LibreTranslate"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: git clone nas-tools
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git clone --depth=1 https://github.com/LibreTranslate/LibreTranslate /workdir

    - name: Build and Push
      uses: docker/build-push-action@master
      with:
        build_args: with_models=true
        context: /workdir
        file: /workdir/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: xiami110/LibreTranslate:latest
