[observability]
log-level = "info"

[[source]]
mode = "server"
address = "ntp.ntsc.ac.cn"

[[source]]
mode = "server"
address = "ntp.cnnic.cn"

[[source]]
mode = "server"
address = "ntp.aliyun.com"

[[source]]
mode = "server"
address = "cn.ntp.org.cn"

[[server]]
listen = "0.0.0.0:123"

[synchronization]
single-step-panic-threshold = 1800
startup-step-panic-threshold = { forward="inf", backward = 1800 }
