version: '3'
services:
  frpc:
    image: xiami110/frpc
    container_name: frpc
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/frpc/frpc.ini:/etc/frp/frpc.ini
