version: '3'
services:
  cloudreve:
    image: xiami110/cloudreve
    container_name: cloudreve
    restart: always
    network_mode: mynet
    logging: 
            options: 
                max-size: 1m
    volumes:
      - "$PWD/uploads:/root/cloudreve/uploads"
      - "$PWD/downloads:/downloads"
      - "$PWD/config:/root/cloudreve/config"
      - "$PWD/db:/root/cloudreve/db"
      - "$PWD/avatar:/root/cloudreve/avatar"
