version: '3'
services:
  cloudreve:
    image: xiami110/cloudreve
    container_name: cloudreve
    restart: always
    network_mode: mynet
    logging: 
            options: 
                max-size: 1m
    devices:
      - "$PWD/uploads:/cloudreve/uploads"
      - "$PWD/downloads:/downloads"
      - "$PWD/config:/cloudreve/config"
      - "$PWD/db:/cloudreve/db"
      - "$PWD/avatar:/cloudreve/avatar"
