name: Auto Build
run-name: "Auto Build ${{ inputs.repo }}:${{ inputs.ver }}"

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      ver:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@master
      with:
        context: ./${{ github.event.inputs.repo }}
        file: ./${{ github.event.inputs.repo }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          xiami110/${{ github.event.inputs.repo }}:latest
          xiami110/${{ github.event.inputs.repo }}:${{ github.event.inputs.ver }}
          
    - name: Delete Workflow History
      uses: Mattraks/delete-workflow-runs@main
      with:
        keep_minimum_runs: 2
