name: Auto Build
run-name: "Auto Build ${{ inputs.repo }}:${{ inputs.ver }}"

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      ver:
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false # Github Token仅用于拉取代码，完成后从本地删除

    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Login to DockerHub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Login to the Github Container registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: 97xiami
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
      with:
        images: |
          ${{ secrets.USER_NAME }}/${{ github.event.inputs.repo }}
          ghcr.io/97xiami/${{ github.event.inputs.repo }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ github.event.inputs.ver }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      with:
        context: ./${{ github.event.inputs.repo }}
        file: ./${{ github.event.inputs.repo }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-name: ghcr.io/97xiami/${{ github.event.inputs.repo }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Delete ghcr.io buildcache containers
      uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
      with:
        package-name: ${{ github.event.inputs.repo }}
        package-type: 'container'
        delete-only-untagged-versions: 'true'
