name: Auto Build
run-name: "Auto Build ${{ inputs.repo }}:${{ inputs.ver }}"

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      ver:
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      attestations: write
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false # Github Token仅用于拉取代码，完成后从本地删除

    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

    - name: Login to DockerHub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Login to the Github Container registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ghcr.io
        username: 97xiami
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
      with:
        images: |
          ${{ secrets.USER_NAME }}/${{ github.event.inputs.repo }}
          ghcr.io/97xiami/${{ github.event.inputs.repo }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ github.event.inputs.ver }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        context: ./${{ github.event.inputs.repo }}
        file: ./${{ github.event.inputs.repo }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-name: ghcr.io/97xiami/${{ github.event.inputs.repo }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Delete ghcr.io buildcache containers
      uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
      with:
        package-name: ${{ github.event.inputs.repo }}
        package-type: 'container'
        delete-only-untagged-versions: 'true'
