name: Auto Build
run-name: "Auto Build ${{ inputs.repo }}:${{ inputs.ver }}"

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      ver:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.USER_NAME }}/${{ github.event.inputs.name }}
          ghcr.io/${{ github.actor }}/${{ github.event.inputs.name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ github.event.inputs.ver }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ github.event.inputs.repo }}
        file: ./${{ github.event.inputs.repo }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
          
    - name: Delete Workflow History
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 7
        keep_minimum_runs: 5
