name: nas-tools
run-name: "Docker Build: nas-tools"

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
        persist-credentials: false # Github Token仅用于拉取代码，完成后从本地删除

    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

    - name: Login to DockerHub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: git clone nas-tools
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git clone --depth=1 https://github.com/97xiami/nas-tools /workdir

    - name: Build and Push
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        context: /workdir
        file: /workdir/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: xiami110/nas-tools:2.9.1
