name: One
run-name: "Docker Build: ${{ inputs.name }}"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Dir Name'
        required: true
        type: choice
        options:
          - 'ariang'
          - 'frpc'
          - 'frps'
          - 'kms'
          - 'libretranslate'
          - 'mind-map'
          - 'qbittorrentee'
          - 'samba'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.USER_NAME }}/${{ github.event.inputs.name }}
          ghcr.io/${{ github.actor }}/${{ github.event.inputs.name }}
        tags: |
          type=raw,value=latest

    - name: echo
      run: |
        echo "${{ steps.meta.outputs.tags }}"
        echo "${{ steps.meta.outputs.labels }}"

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./${{ github.event.inputs.name }}
        file: ./${{ github.event.inputs.name }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ github.actor }}/${{ github.event.inputs.name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Delete all containers from package without tags
      uses: Chizkiyahu/delete-untagged-ghcr-action@v5
      with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: ${{ github.event.inputs.name }}
          untagged_only: true
          owner_type: user
