name: One
run-name: "Docker Build: ${{ inputs.name }}-${{ inputs.arch }}"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Dir Name"
        required: true
        type: choice
        options:
          - "aria2"
          - "ariang"
          - "frpc"
          - "frps"
          - "kms"
          - "mind-map"
          - "mindustry"
          - "ntpd-rs"
          - "openlist"
          - "oxidns"
          - "qbittorrentee"
          - "samba"
      arch:
        description: "Target Arch"
        required: true
        type: choice
        default: "ubuntu-24.04"
        options:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"

permissions: {}

jobs:
  build:
    runs-on: ${{ github.event.inputs.arch }}
    steps:
      - uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit # 多次运行后改为block+白名单
          # allowed-endpoints:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: true # Github Token仅用于拉取代码，完成后从本地删除

      - name: Hadolint Check
        uses: hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6 # v3.4.0
        with:
          dockerfile: ${{ github.event.inputs.name }}/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./${{ github.event.inputs.name }}
          file: ./${{ github.event.inputs.name }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.USER_NAME }}/${{ github.event.inputs.name }}:test
