name: One
run-name: "Docker Build: ${{ inputs.name }}"

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: "ssh connect"
        required: true
        type: boolean
        default: false
      name:
        description: "Dir Name"
        required: true
        type: choice
        options:
          - "aria2"
          - "ariang"
          - "frpc"
          - "frps"
          - "kms"
          - "mind-map"
          - "mindustry"
          - "ntpd-rs"
          - "openlist"
          - "qbittorrentee"
          - "samba"
      arch:
        description: "Target Arch"
        required: true
        type: choice
        default: "linux/amd64"
        options:
          - "linux/amd64"
          - "linux/arm64"
          - "linux/amd64,linux/arm64"

      tag:
        description: "Target Tag"
        required: true
        type: choice
        default: "test"
        options:
          - "latest"
          - "test"

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # 多次运行后改为block+白名单
          # allowed-endpoints:

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false # Github Token仅用于拉取代码，完成后从本地删除

      - name: Hadolint Check
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ${{ github.event.inputs.name }}/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to DockerHub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./${{ github.event.inputs.name }}
          file: ./${{ github.event.inputs.name }}/Dockerfile
          platforms: ${{ github.event.inputs.arch }}
          push: true
          tags: |
            ${{ secrets.USER_NAME }}/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}
