name: One
run-name: "Docker Build: ${{ inputs.name }}"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Dir Name'
        required: true
        type: choice
        options:
          - 'frpc'
          - 'frps'
          - 'kms'
          - 'mind-map'
          - 'qbittorrentee'
          - 'samba'

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          xiami110/${{ github.event.inputs.repo }}
          ${{ github.actor }}/${{ github.event.inputs.repo }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build and Push
      uses: docker/build-push-action@master
      with:
        context: ./${{ github.event.inputs.name }}
        file: ./${{ github.event.inputs.name }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
