name: One
run-name: "Docker Build: ${{ inputs.name }}"

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: "ssh connect"
        required: true
        type: boolean
        default: false
      name:
        description: 'Dir Name'
        required: true
        type: choice
        options:
          - 'aria2'
          - 'ariang'
          - 'arya'
          - 'frpc'
          - 'frps'
          - 'kms'
          - 'libretranslate'
          - 'mind-map'
          - 'minipaint'
          - 'qbittorrentee'
          - 'samba'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
      if: ${{ github.event.inputs.ssh == 'true' }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./${{ github.event.inputs.name }}
        file: ./${{ github.event.inputs.name }}/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.USER_NAME }}/${{ github.event.inputs.name }}:latest
          ghcr.io/${{ github.actor }}/${{ github.event.inputs.name }}:latest
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ github.actor }}/${{ github.event.inputs.name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Delete vaultwarden-buildcache containers
      uses: actions/delete-package-versions@v5
      with:
        package-name: ${{ github.event.inputs.name }}
        package-type: 'container'
        delete-only-untagged-versions: 'true'
