name: Update Checker

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        repo: [ aria2, mayswind/AriaNg, frpc, frps, wanglin2/mind-map, viliusle/miniPaint, c0re100/qBittorrent-Enhanced-Edition, samba]
        
    steps:          
    - name: Get Latest Release Tag
      id: get_tag
      run: |
        if [ "aria2" == "${{ matrix.repo }}" ] || [ "samba" == "${{ matrix.repo }}" ]; then
          latest_release=$(curl -s https://pkgs.alpinelinux.org/packages?name=${{ matrix.repo }} | sed -n 's/.*<strong[^>]*>\(.*\)<\/strong>.*/\1/p')
          echo "Latest release tag: $latest_release"
          echo "tag=$latest_release" >> $GITHUB_OUTPUT
        elif [ "frpc" == "${{ matrix.repo }}" ] || [ "frps" == "${{ matrix.repo }}" ]; then
          latest_release=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | jq -r .tag_name)
          echo "Latest release tag: $latest_release"
          echo "tag=$latest_release" >> $GITHUB_OUTPUT
        else
          latest_release=$(curl -s https://api.github.com/repos/${{ matrix.repo }}/releases/latest | jq -r .tag_name)
          echo "Latest release tag: $latest_release"
          echo "tag=$latest_release" >> $GITHUB_OUTPUT
        fi

    - name: Cache Tag
      id: cache_tag
      uses: actions/cache@v4
      with:
        path: release.txt
        key: ${{ matrix.repo }}:${{ steps.get_tag.outputs.tag }}

    - name: Compare Tags
      id: compare_tags
      run: |
        if [ ! -f release.txt ]; then
          touch release.txt
        fi
        cached_tag=$(cat release.txt || echo "")
        if [ "$cached_tag" != "${{ steps.get_tag.outputs.tag }}" ]; then
          echo "tags_different=true" >> $GITHUB_OUTPUT
        else
          echo "tags_different=false" >> $GITHUB_OUTPUT
        fi

    - name: Save New Tag
      if: steps.compare_tags.outputs.tags_different == 'true'
      run: |
        echo ${{ steps.get_tag.outputs.tag }} | tee release.txt

    - name: Create
      if: steps.compare_tags.outputs.tags_different == 'true'
      id: dirname
      run: |
        if [ "aria2" == "${{ matrix.repo }}" ]; then
          echo "dir=aria2" >> $GITHUB_OUTPUT

        elif [ "mayswind/AriaNg" == "${{ matrix.repo }}" ]; then
          echo "dir=ariang" >> $GITHUB_OUTPUT

        elif [ "frpc" == "${{ matrix.repo }}" ]; then
          echo "dir=frpc" >> $GITHUB_OUTPUT

        elif [ "frps" == "${{ matrix.repo }}" ]; then
          echo "dir=frps" >> $GITHUB_OUTPUT
          
        elif [ "wanglin2/mind-map" == "${{ matrix.repo }}" ]; then
          echo "dir=mind-map" >> $GITHUB_OUTPUT
          
        elif [ "viliusle/miniPaint" == "${{ matrix.repo }}" ]; then
          echo "dir=minipaint" >> $GITHUB_OUTPUT
          
        elif [ "c0re100/qBittorrent-Enhanced-Edition" == "${{ matrix.repo }}" ]; then
          echo "dir=qbittorrentee" >> $GITHUB_OUTPUT
          
        elif [ "samba" == "${{ matrix.repo }}" ]; then
          echo "dir=samba" >> $GITHUB_OUTPUT
          
        fi

    - name: Call Another Workflow
      if: steps.compare_tags.outputs.tags_different == 'true' && steps.dirname.outputs.dir != ''
      uses: actions/github-script@v7
      with:
        script: |
          const response = await github.rest.actions.createWorkflowDispatch({
            owner: '97xiami',
            repo: 'Dockerfiles',
            workflow_id: 'AutoBuild.yml',
            ref: 'main',
            inputs: {
              repo: '${{ steps.dirname.outputs.dir }}',
              ver: '${{ steps.get_tag.outputs.tag }}'
            }
          });
          console.log(response);
